apiVersion: v1
kind: Pod
metadata:
  name: mynginxpod
  labels:
    app: my-app

spec:
  containers:
    - image: nginx
      name: nginxcontainer
      ports:
        - containerPort: 80
          hostPort: 80
