apiVersion: v1
kind: Pod
metadata:
  name: mynginxpod
  labels:
    app: my-app
    env: my-env

spec:
  containers:
    - image: nginx
      name: nginxcontainer
      ports:
        - containerPort: 80
          hostPort: 80
  nodeSelector:
    gpu: "true"

